name: Generate and Publish TEST Schema Documentation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  process_schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r resources/requirements.txt

    - name: Generate Schema Documentation
      run: |
        python resources/generate_current_schema_documentation.py --source-dir $GITHUB_WORKSPACE

    - name: Commit and push changes
      run: |
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config user.name "${GITHUB_ACTOR}"
        git add markdown/
        git add site/  
        git commit -am "Regenerated docs based on schema updates"
        git push origin HEAD:${{ github.event.pull_request.base.ref }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site


